//! Representation layer — transforms world state into views.
//!
//! The world returns structured state (the `details` field of UnifiedResult).
//! This module transforms that state into different representations:
//!
//!   json    — raw structured state (for agents, pipes)
//!   pretty  — colored human-readable (for terminals)
//!   quiet   — nothing (exit code only)
//!
//! This is a representation add-on: it does not change the world,
//! it changes how the world is presented.

use colored::Colorize;
use serde_json::json;

use crate::contracts::UnifiedResult;
use crate::plugin::PluginRegistry;

// ─── Representation mode ────────────────────────────────────────────────────

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum OutputMode {
    /// Raw structured state — for agents and pipes.
    Json,
    /// Colored human-readable — for terminals.
    Pretty,
    /// Nothing — exit code only.
    Quiet,
}

// ─── World state representation ─────────────────────────────────────────────

/// Represent a world result (observe or act).
///
/// The world returns `UnifiedResult` which contains:
///   - `details`: structured state (the world)
///   - `output`: prose summary (representation concern)
///   - `error`: error info
///   - `risk`, `next_suggested_actions`: add-on concerns
///
/// JSON mode returns only `details` (and `error` if present) — pure state.
/// Pretty mode uses `output` as a summary and formats `details`.
pub fn format_result(mode: OutputMode, result: &UnifiedResult) {
    match mode {
        OutputMode::Quiet => {}
        OutputMode::Json => {
            // Pure state: just details and error.
            let mut obj = serde_json::Map::new();
            if let Some(err) = &result.error {
                obj.insert(
                    "error".into(),
                    serde_json::to_value(err).unwrap_or_default(),
                );
            }
            if let Some(details) = &result.details {
                obj.insert("details".into(), details.clone());
            }
            println!(
                "{}",
                serde_json::to_string_pretty(&serde_json::Value::Object(obj))
                    .unwrap_or_default()
            );
        }
        OutputMode::Pretty => {
            format_result_pretty(result);
        }
    }
}

fn format_result_pretty(result: &UnifiedResult) {
    if let Some(err) = &result.error {
        eprintln!("{} [{}] {}", "ERROR".red().bold(), err.code, err.message);
        if let Some(blocked) = &err.blocked_by {
            eprintln!("  {} {:?}", "Blocked by:".dimmed(), blocked);
        }
        return;
    }

    // Summary line (representation of state, generated by adapter)
    if !result.output.is_empty() {
        println!("{}", result.output);
    }

    // Structured details
    if let Some(details) = &result.details {
        if let Some(obj) = details.as_object() {
            for (key, val) in obj {
                format_field(key, val, 2);
            }
        }
    }
}

fn format_field(key: &str, val: &serde_json::Value, indent: usize) {
    let pad = " ".repeat(indent);
    match val {
        serde_json::Value::Array(arr) => {
            println!("{pad}{} ({} items)", key.cyan(), arr.len());
            for item in arr.iter().take(10) {
                if let Some(s) = item.as_str() {
                    println!("{pad}  - {s}");
                } else if let Some(obj) = item.as_object() {
                    let summary: Vec<String> = obj
                        .iter()
                        .take(4)
                        .map(|(k, v)| format!("{}={}", k, format_value_short(v)))
                        .collect();
                    println!("{pad}  - {}", summary.join(", "));
                } else {
                    println!("{pad}  - {}", format_value_short(item));
                }
            }
            if arr.len() > 10 {
                println!(
                    "{pad}  {}",
                    format!("...{} more...", arr.len() - 10).dimmed()
                );
            }
        }
        serde_json::Value::Bool(b) => {
            let display = if *b {
                "true".green()
            } else {
                "false".red()
            };
            println!("{pad}{} {}", key.cyan(), display);
        }
        serde_json::Value::String(s) => {
            println!("{pad}{} {s}", key.cyan());
        }
        serde_json::Value::Number(n) => {
            println!("{pad}{} {n}", key.cyan());
        }
        _ => {
            println!("{pad}{} {}", key.cyan(), format_value_short(val));
        }
    }
}

fn format_value_short(v: &serde_json::Value) -> String {
    match v {
        serde_json::Value::String(s) => {
            if s.len() > 60 {
                format!("{}...", &s[..57])
            } else {
                s.clone()
            }
        }
        serde_json::Value::Null => "null".to_string(),
        serde_json::Value::Bool(b) => b.to_string(),
        serde_json::Value::Number(n) => n.to_string(),
        serde_json::Value::Array(arr) => format!("[{} items]", arr.len()),
        serde_json::Value::Object(obj) => format!("{{{} keys}}", obj.len()),
    }
}

// ─── Spec representation ────────────────────────────────────────────────────

pub fn format_spec(
    mode: OutputMode,
    domain_str: Option<&str>,
    core_only: bool,
    registry: &PluginRegistry,
) {
    let include_addons = !core_only;

    // Collect specs from all plugins in the registry
    let mut specs: Vec<serde_json::Value> = Vec::new();

    if let Some(ds) = domain_str {
        // Specific domain requested
        if let Some(plugin) = registry.get(ds) {
            let mut spec = plugin.spec().clone();
            if include_addons {
                layer_addons(&mut spec, ds);
            }
            specs.push(spec);
        } else {
            eprintln!("Unknown domain: {ds}");
            return;
        }
    } else {
        // All domains
        for plugin in registry.all() {
            let mut spec = plugin.spec().clone();
            if include_addons {
                layer_addons(&mut spec, plugin.domain());
            }
            specs.push(spec);
        }
    }

    match mode {
        OutputMode::Quiet => {}
        OutputMode::Json => {
            if specs.len() == 1 {
                println!(
                    "{}",
                    serde_json::to_string_pretty(&specs[0]).unwrap_or_default()
                );
            } else {
                println!(
                    "{}",
                    serde_json::to_string_pretty(&specs).unwrap_or_default()
                );
            }
        }
        OutputMode::Pretty => {
            for s in &specs {
                let domain_name = s["domain"].as_str().unwrap_or("?");
                println!("{}", domain_name.cyan().bold());

                if let Some(obs) = s.get("observations") {
                    if let Some(obj) = obs.as_object() {
                        if !obj.is_empty() {
                            println!("  {}", "observations:".dimmed());
                            for (key, val) in obj {
                                let type_str = summarize_type(val);
                                println!("    {} {}", key.white(), type_str.dimmed());
                            }
                        }
                    }
                }

                print_actions_pretty(s);

                if let Some(addons) = s.get("addons") {
                    if let Some(obj) = addons.as_object() {
                        for (addon_name, addon_spec) in obj {
                            println!(
                                "  {} {}:",
                                "addon".dimmed(),
                                addon_name.yellow().bold()
                            );
                            print_addon_spec_inline(addon_name, addon_spec);
                        }
                    }
                }

                println!();
            }
        }
    }
}

/// Layer addon contributions onto a spec if the domain has addon support.
fn layer_addons(spec: &mut serde_json::Value, domain_str: &str) {
    use crate::contracts::observe::ObserveDomain;

    // Addons use ObserveDomain — only native domains get addon contributions
    let domain: Result<ObserveDomain, _> =
        serde_json::from_value(serde_json::Value::String(domain_str.to_string()));

    if let Ok(domain) = domain {
        let addons_registered = super::addons::registered();
        let mut addon_specs = serde_json::Map::new();
        for addon in &addons_registered {
            if let Some(addon_spec) = addon.domain_spec(domain) {
                addon_specs.insert(addon.name().to_string(), addon_spec);
            }
        }
        if !addon_specs.is_empty() {
            spec.as_object_mut()
                .unwrap()
                .insert("addons".into(), serde_json::Value::Object(addon_specs));
        }
    }
}

fn print_actions_pretty(s: &serde_json::Value) {
    if let Some(actions) = s.get("actions") {
        if let Some(arr) = actions.as_array() {
            if !arr.is_empty() {
                println!("  {}", "actions:".dimmed());
                for action in arr {
                    let target = action["target"].as_str().unwrap_or("?");
                    let verbs_arr = action["verbs"]
                        .as_array()
                        .map(|a| {
                            a.iter()
                                .filter_map(|v| v.as_str())
                                .collect::<Vec<_>>()
                                .join(", ")
                        })
                        .unwrap_or_default();
                    let desc = action["description"].as_str().unwrap_or("");

                    // Show args schema if present
                    let args_hint = action.get("args").and_then(|a| a.as_object()).map(|obj| {
                        obj.iter()
                            .map(|(k, v)| {
                                if let Some(enum_vals) =
                                    v.get("enum").and_then(|e| e.as_array())
                                {
                                    let vals: Vec<&str> = enum_vals
                                        .iter()
                                        .filter_map(|e| e.as_str())
                                        .collect();
                                    format!("{}={}", k, vals.join("|"))
                                } else {
                                    let t = v.get("type").and_then(|t| t.as_str()).unwrap_or("string");
                                    format!("{}=<{}>", k, t)
                                }
                            })
                            .collect::<Vec<_>>()
                            .join(" ")
                    });

                    if let Some(hint) = args_hint {
                        println!(
                            "    {} [{}] {} {}",
                            target.white(),
                            verbs_arr.green(),
                            hint.yellow(),
                            desc.dimmed()
                        );
                    } else {
                        println!(
                            "    {} [{}] {}",
                            target.white(),
                            verbs_arr.green(),
                            desc.dimmed()
                        );
                    }
                }
            }
        }
    }
}

fn print_addon_spec_inline(name: &str, spec: &serde_json::Value) {
    match name {
        "verify" => {
            if let Some(preds) = spec.get("predicates").and_then(|p| p.as_array()) {
                for pred in preds {
                    let pname = pred["name"].as_str().unwrap_or("?");
                    let asserts = pred["asserts"].as_str().unwrap_or("");
                    println!("      {} {}", pname.white(), asserts.dimmed());
                }
            }
        }
        "policy" => {
            if let Some(rules) = spec.get("rules").and_then(|r| r.as_array()) {
                for rule in rules {
                    let target = rule["target"].as_str().unwrap_or("?");
                    let verb = rule["verb"].as_str().unwrap_or("?");
                    let class = rule["classification"].as_str().unwrap_or("?");
                    let consent = rule
                        .get("requires_consent")
                        .and_then(|c| c.as_bool())
                        .unwrap_or(false);
                    let badge = match class {
                        "low" => class.green(),
                        "medium" => class.yellow(),
                        "high" => class.red(),
                        _ => class.normal(),
                    };
                    let label = format!("{target} {verb}");
                    if consent {
                        println!(
                            "      {} {} {}",
                            label.white(),
                            badge,
                            "(requires --yes)".dimmed()
                        );
                    } else {
                        println!("      {} {}", label.white(), badge);
                    }
                }
            }
        }
        _ => {
            if let Some(obj) = spec.as_object() {
                for (k, v) in obj {
                    println!("      {}: {}", k.white(), format_value_short(v).dimmed());
                }
            }
        }
    }
}

// ─── Tools representation ───────────────────────────────────────────────────

pub fn format_tools(mode: OutputMode) {
    let tools = vec![
        (
            "observe",
            "Read-only structured system state (O)",
            "world observe <domain> [--scope ...] [--target ...]",
        ),
        (
            "act",
            "Finite verbs on schema paths (A)",
            "world act <domain> <target> <verb> [key=value ...]",
        ),
        (
            "spec",
            "POMDP definition — observations + actions + add-ons",
            "world spec [domain] [--core]",
        ),
    ];

    match mode {
        OutputMode::Quiet => {}
        OutputMode::Json => {
            let json_tools: Vec<serde_json::Value> = tools
                .iter()
                .map(|(name, desc, usage)| {
                    json!({ "name": name, "description": desc, "usage": usage })
                })
                .collect();
            println!(
                "{}",
                serde_json::to_string_pretty(&json!({
                    "tools": json_tools,
                }))
                .unwrap_or_default()
            );
        }
        OutputMode::Pretty => {
            println!("{}", "world — POMDP interface for agents".bold());
            println!();
            println!("{}", "Commands:".dimmed());
            for (name, desc, usage) in &tools {
                println!("  {} — {}", name.cyan().bold(), desc);
                println!("    {}", usage.dimmed());
            }
            println!();
            println!(
                "{}",
                "Verbs are defined per-domain in the spec. Run `world spec` to see them."
                    .dimmed()
            );
            println!(
                "{}",
                "Policy (risk classification, consent gates) is enforced by the policy add-on."
                    .dimmed()
            );
        }
    }
}

// ─── Add-ons representation ─────────────────────────────────────────────────

pub fn format_addons(mode: OutputMode, name: Option<&str>, domain_str: Option<&str>) {
    use super::addons;
    use crate::contracts::observe::ObserveDomain;

    let registered = addons::registered();

    match mode {
        OutputMode::Quiet => {}
        OutputMode::Json => {
            if let Some(addon_name) = name {
                let addon = registered.iter().find(|a| a.name() == addon_name);
                match addon {
                    Some(a) => {
                        if let Some(ds) = domain_str {
                            let domain: Result<ObserveDomain, _> =
                                serde_json::from_value(serde_json::Value::String(ds.to_string()));
                            match domain {
                                Ok(d) => {
                                    let spec =
                                        a.domain_spec(d).unwrap_or(serde_json::json!(null));
                                    println!(
                                        "{}",
                                        serde_json::to_string_pretty(&serde_json::json!({
                                            "addon": a.name(),
                                            "kind": a.kind(),
                                            "domain": d.as_str(),
                                            "spec": spec,
                                        }))
                                        .unwrap_or_default()
                                    );
                                }
                                Err(_) => eprintln!("Unknown domain: {ds}"),
                            }
                        } else {
                            let domain_specs: Vec<serde_json::Value> =
                                crate::spec::SPEC_DOMAINS
                                    .iter()
                                    .filter_map(|d| {
                                        a.domain_spec(*d).map(|s| {
                                            serde_json::json!({
                                                "domain": d.as_str(),
                                                "spec": s,
                                            })
                                        })
                                    })
                                    .collect();
                            println!(
                                "{}",
                                serde_json::to_string_pretty(&serde_json::json!({
                                    "addon": a.name(),
                                    "kind": a.kind(),
                                    "description": a.description(),
                                    "domains": domain_specs,
                                }))
                                .unwrap_or_default()
                            );
                        }
                    }
                    None => eprintln!("Unknown add-on: {addon_name}"),
                }
            } else {
                let list: Vec<serde_json::Value> = registered
                    .iter()
                    .map(|a| {
                        serde_json::json!({
                            "name": a.name(),
                            "kind": a.kind(),
                            "description": a.description(),
                        })
                    })
                    .collect();
                println!("{}", serde_json::to_string_pretty(&list).unwrap_or_default());
            }
        }
        OutputMode::Pretty => {
            if let Some(addon_name) = name {
                let addon = registered.iter().find(|a| a.name() == addon_name);
                match addon {
                    Some(a) => {
                        println!("{} — {}", a.name().cyan().bold(), a.description());
                        println!("  {} {:?}", "kind:".dimmed(), a.kind());
                        println!();

                        let domains: Vec<ObserveDomain> = if let Some(ds) = domain_str {
                            match serde_json::from_value(serde_json::Value::String(
                                ds.to_string(),
                            )) {
                                Ok(d) => vec![d],
                                Err(_) => {
                                    eprintln!("Unknown domain: {ds}");
                                    return;
                                }
                            }
                        } else {
                            crate::spec::SPEC_DOMAINS.to_vec()
                        };

                        for d in &domains {
                            if let Some(addon_spec) = a.domain_spec(*d) {
                                println!("  {}:", d.as_str().white().bold());
                                print_addon_spec_inline(a.name(), &addon_spec);
                            }
                        }
                    }
                    None => eprintln!("Unknown add-on: {addon_name}"),
                }
            } else {
                println!("{}", "Registered add-ons:".bold());
                println!();
                for a in &registered {
                    println!(
                        "  {} [{}] — {}",
                        a.name().cyan().bold(),
                        format!("{:?}", a.kind()).dimmed(),
                        a.description()
                    );
                }
                println!();
                println!(
                    "{}",
                    "Use `world addons <name>` for details, or `world spec` to see add-ons in context."
                        .dimmed()
                );
            }
        }
    }
}

// ─── Type helpers ───────────────────────────────────────────────────────────

fn summarize_type(val: &serde_json::Value) -> String {
    match val {
        serde_json::Value::String(s) => s.clone(),
        serde_json::Value::Array(arr) => {
            if let Some(s) = arr.first().and_then(|v| v.as_str()) {
                format!("[{s}]")
            } else {
                "[...]".to_string()
            }
        }
        serde_json::Value::Object(obj) => {
            if let Some(t) = obj.get("type").and_then(|v| v.as_str()) {
                if t == "array" {
                    format!(
                        "[{} ...]",
                        obj.get("item").map(|_| "object").unwrap_or("?")
                    )
                } else {
                    t.to_string()
                }
            } else {
                let keys: Vec<&String> = obj.keys().take(4).collect();
                format!(
                    "{{ {} }}",
                    keys.iter()
                        .map(|k| k.as_str())
                        .collect::<Vec<_>>()
                        .join(", ")
                )
            }
        }
        _ => format!("{val}"),
    }
}
